### ISSUE TITLE
使用 express 转发 HTTP 请求到 PHP-FPM，当 HTTP 包体过大时，出错

### ISSUE THREAD

**Issue by gamelife1314** [LastLeaf/node-fastcgi-client#7]
https://github.com/LastLeaf/node-fastcgi-client/blob/fadbd3398a7baee93873fca1ed759152b4673376/lib/request.js#L177

您好，我准备将我的 PHP 程序升级为 NodeJS，思路是使用 express 框架通过一个中间件将某些请求转发至 PHP-FPM处理，新的API交友NodeJS处理。但是在转发 HTTP 请求过程中，由于某些 HTTP 包体过大，底层会使用多个 TCP 包来发送，所以 `stdin._write` 会被调用多次，这样的话， `stdin._write`  中的 `cb` 就会被调用多次，然后系统就报错了：

```
_stream_writable.js:456
    throw new ERR_MULTIPLE_CALLBACK();
    ^

Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at onwrite (_stream_writable.js:456:11)
    at afterWrite (_stream_writable.js:485:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

这是我写的 express 中间件代码，请帮忙解答一下疑问，感激不尽

```javascript
const path = require('path');

const fastCGIClient = require('fastcgi-client');

const defaultOptions = {
    host: '127.0.0.1',
    port: 9000,
    documentRoot: path.dirname(require.main.filename || '.'),
    skipCheckServer: true,
};

module.exports = function(options = {}, input_fastcgi_params = {}) {

    options = Object.assign({}, defaultOptions, options);
    const fpm = new Promise((resolve, reject) => {

        const loader = fastCGIClient(options);
        loader.on('ready', () => resolve(loader));
        loader.on('error', reject);
    });

    return async function(req, res, next) {

        // 以 /api/node 开始的请求全部由 express 处理
        if (req.url.startsWith('/api/node')) {
            return next();
        }
        
        let [_, ...queryString] = req.url.split('?');
        queryString = queryString ? queryString[0] : '';

        let fastcgi_params = Object.assign({}, input_fastcgi_params, {
            REQUEST_URI: `/index.php${req.url}`,
            DOCUMENT_URI: '/index.php',
            SCRIPT_NAME: '/index.php',
            QUERY_STRING: queryString,
            REQUEST_METHOD: req.method,
            CONTENT_TYPE: req.headers['content-type'],
            CONTENT_LENGTH: req.headers['content-length'],
            SERVER_PROTOCOL: 'HTTP/1.1',
            REQUEST_SCHEME: req.protocol,
            HTTPS: req.protocol === 'https' ? 'on': undefined,
            GATEWAY_INTERFACE: 'CGI/1.1',
            SERVER_SOFTWARE: 'PHP-FPM FOR Node',
            REMOTE_ADDR: req.connection.remoteAddress,
            REMOTE_PORT:  req.connection.remotePort,
            SERVER_NAME: req.connection.domain,
            REDIRECT_STATUS: 200,

            // 下面的由外部传入
            // SERVER_ADDR: 127.0.0.1,
            // SERVER_PORT: 8080,
            // DOCUMENT_ROOT: /var/www/public
            // SCRIPT_FILENAME: /var/www/public/index.php
        });

         if (! fastcgi_params.REQUEST_URI || ! fastcgi_params.REQUEST_URI.startsWith('/')) {
             throw new Error('Invalid URI');
         }

         for (const fastcgi_param in fastcgi_params) {
             if (typeof fastcgi_params[fastcgi_param] === 'undefined') {
                 delete fastcgi_params[fastcgi_param];
             }
         }

         console.log(fastcgi_params);

         const phpFPM = await fpm;

         return new Promise(function(resolve, reject) {
             
            phpFPM.request(fastcgi_params, function(err, request) {
                
                if (err) return reject(err);

                var output = '';
                var errors = '';

                // console.log(req.body);
                // console.log(req.files.file);

                req.on('end', function(){
                    console.log('没有数据了');
                });

                req.on('data', function(chunk) {
                    // console.log(chunk.toString());
                    console.log(`接收到 ${chunk.length} 个字节的数据`);
                    request.stdin.write(chunk, null, null);
                });

                // request.stdin.on('pipe', function(src) {
                //     console.error('有数据正通过管道流入写入器');
                // });

                request.stdout.on('data', function(data) {
                    output += data.toString('utf-8');
                });

                request.stderr.on('data', function(data) {
                    errors += data.toString('utf-8');
                });

                request.stdout.on('end', function() {
                    
                    if (errors) {
                        return reject(new Error(errors));
                    }

                    const head = output.match(/^[\s\S]*?\r\n\r\n/)[0];
                    const parseHead = head.split('\r\n').filter(_ => _);
                    const responseHeaders = {};
                    let statusCode = 200;
                    let statusMessage = '';
          
                    for (const item of parseHead) {
                        const pair = item.split(': ');
                        
                        if (pair.length > 1 && pair[0] && pair[1]) {
                            if (pair[0] in responseHeaders) {
                                responseHeaders[pair[0]].push(pair[1]);
                            } else {
                                responseHeaders[pair[0]] = [pair[1]];
                            }

                            if (pair[0] === 'Status') {
                                const match = pair[1].match(/(\d+) (.*)/);
                                statusCode = parseInt(match[1]);
                                statusMessage = match[2];
                            }
                        }
                    }
                    res.writeHead(statusCode, statusMessage, responseHeaders);
                    const body = output.slice(head.length);
                    res.write(body);
                    res.end();
                    resolve({ fastcgi_params, body });
                });
            });
         });
    };
};
```

**Comment by LastLeaf** [comment]
抱歉，这段代码过于久远，我现在还没有完全确认原因，之后我仔细排查一下。

现在我推测原因是出现在 https://github.com/LastLeaf/node-fastcgi-client/blob/master/lib/connection.js#L60

可能这个函数在拆分/合并 buffer 的时候多调用了几次 cb 。

如果你有充分的时间来处理的话，可以仔细推敲一下，给我发个 PR 吧。

**Comment by gamelife1314** [comment]
抱歉留言打扰到了您，昨天刚接触 NodeJS，我研究学习一下。

**Comment by LastLeaf** [comment]
这一段代码的逻辑是把内容拆成 0xffff 的分段，通过 socket 发出去之后回调。这里 cb 每次执行 sendMessage 都会被调用。应该改成最后一次执行 sendMessage 再调用。

**Comment by gamelife1314** [comment]
好的，谢谢，我试着改了，没改对，我再研究研究。 michael.fudenglong 邮箱：michael.fudenglong@qq.com 签名由 网易邮箱大师 定制 在2019年04月10日 15:43，LastLeaf 写道： 这一段代码的逻辑是把内容拆成 0xffff 的分段，通过 socket 发出去之后回调。这里 cb 每次执行 sendMessage 都会被调用。应该改成最后一次执行 sendMessage 再调用。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Martin1994** [comment]
#9 should be able to fix this problem

**Comment by LastLeaf** [comment]
> #9 should be able to fix this problem

Thanks!
